#include <windows.h>

extern "C" {

__declspec(dllexport) void EOS_Achievements_AddNotifyAchievementsUnlocked() {}
__declspec(dllexport) void EOS_Achievements_AddNotifyAchievementsUnlockedV2() {}
__declspec(dllexport) void EOS_Achievements_CopyAchievementDefinitionByAchievementId() {}
__declspec(dllexport) void EOS_Achievements_CopyAchievementDefinitionByIndex() {}
__declspec(dllexport) void EOS_Achievements_CopyAchievementDefinitionV2ByAchievementId() {}
__declspec(dllexport) void EOS_Achievements_CopyAchievementDefinitionV2ByIndex() {}
__declspec(dllexport) void EOS_Achievements_CopyPlayerAchievementByAchievementId() {}
__declspec(dllexport) void EOS_Achievements_CopyPlayerAchievementByIndex() {}
__declspec(dllexport) void EOS_Achievements_CopyUnlockedAchievementByAchievementId() {}
__declspec(dllexport) void EOS_Achievements_CopyUnlockedAchievementByIndex() {}
__declspec(dllexport) void EOS_Achievements_DefinitionV2_Release() {}
__declspec(dllexport) void EOS_Achievements_Definition_Release() {}
__declspec(dllexport) void EOS_Achievements_GetAchievementDefinitionCount() {}
__declspec(dllexport) void EOS_Achievements_GetPlayerAchievementCount() {}
__declspec(dllexport) void EOS_Achievements_GetUnlockedAchievementCount() {}
__declspec(dllexport) void EOS_Achievements_PlayerAchievement_Release() {}
__declspec(dllexport) void EOS_Achievements_QueryDefinitions() {}
__declspec(dllexport) void EOS_Achievements_QueryPlayerAchievements() {}
__declspec(dllexport) void EOS_Achievements_RemoveNotifyAchievementsUnlocked() {}
__declspec(dllexport) void EOS_Achievements_UnlockAchievements() {}
__declspec(dllexport) void EOS_Achievements_UnlockedAchievement_Release() {}
__declspec(dllexport) void EOS_ActiveSession_CopyInfo() {}
__declspec(dllexport) void EOS_ActiveSession_GetRegisteredPlayerByIndex() {}
__declspec(dllexport) void EOS_ActiveSession_GetRegisteredPlayerCount() {}
__declspec(dllexport) void EOS_ActiveSession_Info_Release() {}
__declspec(dllexport) void EOS_ActiveSession_Release() {}
__declspec(dllexport) void EOS_AntiCheatClient_AddExternalIntegrityCatalog() {}
__declspec(dllexport) void EOS_AntiCheatClient_AddNotifyClientIntegrityViolated() {}
__declspec(dllexport) void EOS_AntiCheatClient_AddNotifyMessageToPeer() {}
__declspec(dllexport) void EOS_AntiCheatClient_AddNotifyMessageToServer() {}
__declspec(dllexport) void EOS_AntiCheatClient_AddNotifyPeerActionRequired() {}
__declspec(dllexport) void EOS_AntiCheatClient_AddNotifyPeerAuthStatusChanged() {}
__declspec(dllexport) void EOS_AntiCheatClient_BeginSession() {}
__declspec(dllexport) void EOS_AntiCheatClient_EndSession() {}
__declspec(dllexport) void EOS_AntiCheatClient_GetProtectMessageOutputLength() {}
__declspec(dllexport) void EOS_AntiCheatClient_PollStatus() {}
__declspec(dllexport) void EOS_AntiCheatClient_ProtectMessage() {}
__declspec(dllexport) void EOS_AntiCheatClient_ReceiveMessageFromPeer() {}
__declspec(dllexport) void EOS_AntiCheatClient_ReceiveMessageFromServer() {}
__declspec(dllexport) void EOS_AntiCheatClient_RegisterPeer() {}
__declspec(dllexport) void EOS_AntiCheatClient_RemoveNotifyClientIntegrityViolated() {}
__declspec(dllexport) void EOS_AntiCheatClient_RemoveNotifyMessageToPeer() {}
__declspec(dllexport) void EOS_AntiCheatClient_RemoveNotifyMessageToServer() {}
__declspec(dllexport) void EOS_AntiCheatClient_RemoveNotifyPeerActionRequired() {}
__declspec(dllexport) void EOS_AntiCheatClient_RemoveNotifyPeerAuthStatusChanged() {}
__declspec(dllexport) void EOS_AntiCheatClient_UnprotectMessage() {}
__declspec(dllexport) void EOS_AntiCheatClient_UnregisterPeer() {}
__declspec(dllexport) void EOS_AntiCheatServer_AddNotifyClientActionRequired() {}
__declspec(dllexport) void EOS_AntiCheatServer_AddNotifyClientAuthStatusChanged() {}
__declspec(dllexport) void EOS_AntiCheatServer_AddNotifyMessageToClient() {}
__declspec(dllexport) void EOS_AntiCheatServer_BeginSession() {}
__declspec(dllexport) void EOS_AntiCheatServer_EndSession() {}
__declspec(dllexport) void EOS_AntiCheatServer_GetProtectMessageOutputLength() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogEvent() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogGameRoundEnd() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogGameRoundStart() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogPlayerDespawn() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogPlayerRevive() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogPlayerSpawn() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogPlayerTakeDamage() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogPlayerTick() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogPlayerUseAbility() {}
__declspec(dllexport) void EOS_AntiCheatServer_LogPlayerUseWeapon() {}
__declspec(dllexport) void EOS_AntiCheatServer_ProtectMessage() {}
__declspec(dllexport) void EOS_AntiCheatServer_ReceiveMessageFromClient() {}
__declspec(dllexport) void EOS_AntiCheatServer_RegisterClient() {}
__declspec(dllexport) void EOS_AntiCheatServer_RegisterEvent() {}
__declspec(dllexport) void EOS_AntiCheatServer_RemoveNotifyClientActionRequired() {}
__declspec(dllexport) void EOS_AntiCheatServer_RemoveNotifyClientAuthStatusChanged() {}
__declspec(dllexport) void EOS_AntiCheatServer_RemoveNotifyMessageToClient() {}
__declspec(dllexport) void EOS_AntiCheatServer_SetClientDetails() {}
__declspec(dllexport) void EOS_AntiCheatServer_SetClientNetworkState() {}
__declspec(dllexport) void EOS_AntiCheatServer_SetGameSessionId() {}
__declspec(dllexport) void EOS_AntiCheatServer_UnprotectMessage() {}
__declspec(dllexport) void EOS_AntiCheatServer_UnregisterClient() {}
__declspec(dllexport) void EOS_Audio_CreateNewInputStream() {}
__declspec(dllexport) void EOS_Audio_CreateNewOutputStream() {}
__declspec(dllexport) void EOS_Audio_DestroyInputStream() {}
__declspec(dllexport) void EOS_Audio_DestroyOutputStream() {}
__declspec(dllexport) void EOS_Audio_EnableCommunicationsModeOutputDevices() {}
__declspec(dllexport) void EOS_Audio_GetInputDeviceInfo() {}
__declspec(dllexport) void EOS_Audio_GetInputStreamInfo() {}
__declspec(dllexport) void EOS_Audio_GetOutputDeviceInfo() {}
__declspec(dllexport) void EOS_Audio_GetOutputStreamInfo() {}
__declspec(dllexport) void EOS_Audio_IsInputStreamDeviceDisconnected() {}
__declspec(dllexport) void EOS_Audio_IsInputStreamSilent() {}
__declspec(dllexport) void EOS_Audio_QueryInputDevices() {}
__declspec(dllexport) void EOS_Audio_QueryOutputDevices() {}
__declspec(dllexport) void EOS_Audio_RegisterUser() {}
__declspec(dllexport) void EOS_Audio_RemoveNotifyDevicesChanged() {}
__declspec(dllexport) void EOS_Audio_SetFeatureEnabledForInputStream() {}
__declspec(dllexport) void EOS_Audio_SetNotifyDevicesChanged() {}
__declspec(dllexport) void EOS_Audio_StartInputStream() {}
__declspec(dllexport) void EOS_Audio_StartOutputStream() {}
__declspec(dllexport) void EOS_Audio_StopInputStream() {}
__declspec(dllexport) void EOS_Audio_StopOutputStream() {}
__declspec(dllexport) void EOS_Audio_UnregisterUser() {}
__declspec(dllexport) void EOS_Auth_AddNotifyLoginStatusChanged() {}
__declspec(dllexport) void EOS_Auth_CopyIdToken() {}
__declspec(dllexport) void EOS_Auth_CopyUserAuthToken() {}
__declspec(dllexport) void EOS_Auth_DeletePersistentAuth() {}
__declspec(dllexport) void EOS_Auth_GetLoggedInAccountByIndex() {}
__declspec(dllexport) void EOS_Auth_GetLoggedInAccountsCount() {}
__declspec(dllexport) void EOS_Auth_GetLoginStatus() {}
__declspec(dllexport) void EOS_Auth_GetMergedAccountByIndex() {}
__declspec(dllexport) void EOS_Auth_GetMergedAccountsCount() {}
__declspec(dllexport) void EOS_Auth_GetSelectedAccountId() {}
__declspec(dllexport) void EOS_Auth_IdToken_Release() {}
__declspec(dllexport) void EOS_Auth_LinkAccount() {}
__declspec(dllexport) void EOS_Auth_Login() {}
__declspec(dllexport) void EOS_Auth_Logout() {}
__declspec(dllexport) void EOS_Auth_QueryIdToken() {}
__declspec(dllexport) void EOS_Auth_RemoveNotifyLoginStatusChanged() {}
__declspec(dllexport) void EOS_Auth_Token_Release() {}
__declspec(dllexport) void EOS_Auth_VerifyIdToken() {}
__declspec(dllexport) void EOS_Auth_VerifyUserAuth() {}
__declspec(dllexport) void EOS_BeginScopeEvent() {}
__declspec(dllexport) void EOS_BroadcastAudio_CreateNewInputStream() {}
__declspec(dllexport) void EOS_BroadcastAudio_CreateNewOutputStream() {}
__declspec(dllexport) void EOS_BroadcastAudio_DestroyInputStream() {}
__declspec(dllexport) void EOS_BroadcastAudio_DestroyOutputStream() {}
__declspec(dllexport) void EOS_BroadcastAudio_GetCurrentGainLevel() {}
__declspec(dllexport) void EOS_BroadcastAudio_GetCurrentMicAmplitude() {}
__declspec(dllexport) void EOS_BroadcastAudio_GetInputStreamInfo() {}
__declspec(dllexport) void EOS_BroadcastAudio_GetOutputStreamInfo() {}
__declspec(dllexport) void EOS_BroadcastAudio_PushPacketToOutputStream() {}
__declspec(dllexport) void EOS_BroadcastAudio_SetEncoderSettings() {}
__declspec(dllexport) void EOS_BroadcastAudio_SetMicProcessingSettings() {}
__declspec(dllexport) void EOS_BroadcastAudio_StartInputStream() {}
__declspec(dllexport) void EOS_BroadcastAudio_StartOutputStream() {}
__declspec(dllexport) void EOS_BroadcastAudio_StopInputStream() {}
__declspec(dllexport) void EOS_BroadcastAudio_StopOutputStream() {}
__declspec(dllexport) void EOS_ByteArray_ToString() {}
__declspec(dllexport) void EOS_Connect_AddNotifyAuthExpiration() {}
__declspec(dllexport) void EOS_Connect_AddNotifyLoginStatusChanged() {}
__declspec(dllexport) void EOS_Connect_CopyIdToken() {}
__declspec(dllexport) void EOS_Connect_CopyProductUserExternalAccountByAccountId() {}
__declspec(dllexport) void EOS_Connect_CopyProductUserExternalAccountByAccountType() {}
__declspec(dllexport) void EOS_Connect_CopyProductUserExternalAccountByIndex() {}
__declspec(dllexport) void EOS_Connect_CopyProductUserInfo() {}
__declspec(dllexport) void EOS_Connect_CreateDeviceId() {}
__declspec(dllexport) void EOS_Connect_CreateUser() {}
__declspec(dllexport) void EOS_Connect_DeleteDeviceId() {}
__declspec(dllexport) void EOS_Connect_ExternalAccountInfo_Release() {}
__declspec(dllexport) void EOS_Connect_GetExternalAccountMapping() {}
__declspec(dllexport) void EOS_Connect_GetLoggedInUserByIndex() {}
__declspec(dllexport) void EOS_Connect_GetLoggedInUsersCount() {}
__declspec(dllexport) void EOS_Connect_GetLoginStatus() {}
__declspec(dllexport) void EOS_Connect_GetProductUserExternalAccountCount() {}
__declspec(dllexport) void EOS_Connect_GetProductUserIdMapping() {}
__declspec(dllexport) void EOS_Connect_IdToken_Release() {}
__declspec(dllexport) void EOS_Connect_LinkAccount() {}
__declspec(dllexport) void EOS_Connect_Login() {}
__declspec(dllexport) void EOS_Connect_Logout() {}
__declspec(dllexport) void EOS_Connect_QueryExternalAccountMappings() {}
__declspec(dllexport) void EOS_Connect_QueryProductUserIdMappings() {}
__declspec(dllexport) void EOS_Connect_RemoveNotifyAuthExpiration() {}
__declspec(dllexport) void EOS_Connect_RemoveNotifyLoginStatusChanged() {}
__declspec(dllexport) void EOS_Connect_TransferDeviceIdAccount() {}
__declspec(dllexport) void EOS_Connect_UnlinkAccount() {}
__declspec(dllexport) void EOS_Connect_VerifyIdToken() {}
__declspec(dllexport) void EOS_ContinuanceToken_ToString() {}
__declspec(dllexport) void EOS_CustomInvites_AcceptRequestToJoin() {}
__declspec(dllexport) void EOS_CustomInvites_AddNotifyCustomInviteAccepted() {}
__declspec(dllexport) void EOS_CustomInvites_AddNotifyCustomInviteReceived() {}
__declspec(dllexport) void EOS_CustomInvites_AddNotifyCustomInviteRejected() {}
__declspec(dllexport) void EOS_CustomInvites_AddNotifyRequestToJoinAccepted() {}
__declspec(dllexport) void EOS_CustomInvites_AddNotifyRequestToJoinReceived() {}
__declspec(dllexport) void EOS_CustomInvites_AddNotifyRequestToJoinRejected() {}
__declspec(dllexport) void EOS_CustomInvites_AddNotifyRequestToJoinResponseReceived() {}
__declspec(dllexport) void EOS_CustomInvites_AddNotifySendCustomNativeInviteRequested() {}
__declspec(dllexport) void EOS_CustomInvites_FinalizeInvite() {}
__declspec(dllexport) void EOS_CustomInvites_RejectRequestToJoin() {}
__declspec(dllexport) void EOS_CustomInvites_RemoveNotifyCustomInviteAccepted() {}
__declspec(dllexport) void EOS_CustomInvites_RemoveNotifyCustomInviteReceived() {}
__declspec(dllexport) void EOS_CustomInvites_RemoveNotifyCustomInviteRejected() {}
__declspec(dllexport) void EOS_CustomInvites_RemoveNotifyRequestToJoinAccepted() {}
__declspec(dllexport) void EOS_CustomInvites_RemoveNotifyRequestToJoinReceived() {}
__declspec(dllexport) void EOS_CustomInvites_RemoveNotifyRequestToJoinRejected() {}
__declspec(dllexport) void EOS_CustomInvites_RemoveNotifyRequestToJoinResponseReceived() {}
__declspec(dllexport) void EOS_CustomInvites_RemoveNotifySendCustomNativeInviteRequested() {}
__declspec(dllexport) void EOS_CustomInvites_SendCustomInvite() {}
__declspec(dllexport) void EOS_CustomInvites_SendRequestToJoin() {}
__declspec(dllexport) void EOS_CustomInvites_SetCustomInvite() {}
__declspec(dllexport) void EOS_EApplicationStatus_ToString() {}
__declspec(dllexport) void EOS_ENetworkStatus_ToString() {}
__declspec(dllexport) void EOS_EResult_IsOperationComplete() {}
__declspec(dllexport) void EOS_EResult_ToString() {}
__declspec(dllexport) void EOS_Ecom_CatalogItem_Release() {}
__declspec(dllexport) void EOS_Ecom_CatalogOffer_Release() {}
__declspec(dllexport) void EOS_Ecom_CatalogRelease_Release() {}
__declspec(dllexport) void EOS_Ecom_Checkout() {}
__declspec(dllexport) void EOS_Ecom_CopyEntitlementById() {}
__declspec(dllexport) void EOS_Ecom_CopyEntitlementByIndex() {}
__declspec(dllexport) void EOS_Ecom_CopyEntitlementByNameAndIndex() {}
__declspec(dllexport) void EOS_Ecom_CopyItemById() {}
__declspec(dllexport) void EOS_Ecom_CopyItemImageInfoByIndex() {}
__declspec(dllexport) void EOS_Ecom_CopyItemReleaseByIndex() {}
__declspec(dllexport) void EOS_Ecom_CopyLastRedeemedEntitlementByIndex() {}
__declspec(dllexport) void EOS_Ecom_CopyOfferById() {}
__declspec(dllexport) void EOS_Ecom_CopyOfferByIndex() {}
__declspec(dllexport) void EOS_Ecom_CopyOfferImageInfoByIndex() {}
__declspec(dllexport) void EOS_Ecom_CopyOfferItemByIndex() {}
__declspec(dllexport) void EOS_Ecom_CopyTransactionById() {}
__declspec(dllexport) void EOS_Ecom_CopyTransactionByIndex() {}
__declspec(dllexport) void EOS_Ecom_Entitlement_Release() {}
__declspec(dllexport) void EOS_Ecom_GetEntitlementsByNameCount() {}
__declspec(dllexport) void EOS_Ecom_GetEntitlementsCount() {}
__declspec(dllexport) void EOS_Ecom_GetItemImageInfoCount() {}
__declspec(dllexport) void EOS_Ecom_GetItemReleaseCount() {}
__declspec(dllexport) void EOS_Ecom_GetLastRedeemedEntitlementsCount() {}
__declspec(dllexport) void EOS_Ecom_GetOfferCount() {}
__declspec(dllexport) void EOS_Ecom_GetOfferImageInfoCount() {}
__declspec(dllexport) void EOS_Ecom_GetOfferItemCount() {}
__declspec(dllexport) void EOS_Ecom_GetTransactionCount() {}
__declspec(dllexport) void EOS_Ecom_KeyImageInfo_Release() {}
__declspec(dllexport) void EOS_Ecom_QueryEntitlementToken() {}
__declspec(dllexport) void EOS_Ecom_QueryEntitlements() {}
__declspec(dllexport) void EOS_Ecom_QueryOffers() {}
__declspec(dllexport) void EOS_Ecom_QueryOwnership() {}
__declspec(dllexport) void EOS_Ecom_QueryOwnershipBySandboxIds() {}
__declspec(dllexport) void EOS_Ecom_QueryOwnershipToken() {}
__declspec(dllexport) void EOS_Ecom_RedeemEntitlements() {}
__declspec(dllexport) void EOS_Ecom_Transaction_CopyEntitlementByIndex() {}
__declspec(dllexport) void EOS_Ecom_Transaction_GetEntitlementsCount() {}
__declspec(dllexport) void EOS_Ecom_Transaction_GetTransactionId() {}
__declspec(dllexport) void EOS_Ecom_Transaction_Release() {}
__declspec(dllexport) void EOS_EndScopeEvent() {}
__declspec(dllexport) void EOS_EpicAccountId_FromString() {}
__declspec(dllexport) void EOS_EpicAccountId_IsValid() {}
__declspec(dllexport) void EOS_EpicAccountId_ToString() {}
__declspec(dllexport) void EOS_Friends_AcceptInvite() {}
__declspec(dllexport) void EOS_Friends_AddNotifyBlockedUsersUpdate() {}
__declspec(dllexport) void EOS_Friends_AddNotifyFriendsUpdate() {}
__declspec(dllexport) void EOS_Friends_GetBlockedUserAtIndex() {}
__declspec(dllexport) void EOS_Friends_GetBlockedUsersCount() {}
__declspec(dllexport) void EOS_Friends_GetFriendAtIndex() {}
__declspec(dllexport) void EOS_Friends_GetFriendsCount() {}
__declspec(dllexport) void EOS_Friends_GetStatus() {}
__declspec(dllexport) void EOS_Friends_QueryFriends() {}
__declspec(dllexport) void EOS_Friends_RejectInvite() {}
__declspec(dllexport) void EOS_Friends_RemoveNotifyBlockedUsersUpdate() {}
__declspec(dllexport) void EOS_Friends_RemoveNotifyFriendsUpdate() {}
__declspec(dllexport) void EOS_Friends_SendInvite() {}
__declspec(dllexport) void EOS_GetVersion() {}
__declspec(dllexport) void EOS_Initialize() {}
__declspec(dllexport) void EOS_IntegratedPlatformOptionsContainer_Add() {}
__declspec(dllexport) void EOS_IntegratedPlatformOptionsContainer_Release() {}
__declspec(dllexport) void EOS_IntegratedPlatform_AddNotifyUserLoginStatusChanged() {}
__declspec(dllexport) void EOS_IntegratedPlatform_ClearUserPreLogoutCallback() {}
__declspec(dllexport) void EOS_IntegratedPlatform_CreateIntegratedPlatformOptionsContainer() {}
__declspec(dllexport) void EOS_IntegratedPlatform_FinalizeDeferredUserLogout() {}
__declspec(dllexport) void EOS_IntegratedPlatform_RemoveNotifyUserLoginStatusChanged() {}
__declspec(dllexport) void EOS_IntegratedPlatform_SetUserLoginStatus() {}
__declspec(dllexport) void EOS_IntegratedPlatform_SetUserPreLogoutCallback() {}
__declspec(dllexport) void EOS_KWS_AddNotifyPermissionsUpdateReceived() {}
__declspec(dllexport) void EOS_KWS_CopyPermissionByIndex() {}
__declspec(dllexport) void EOS_KWS_CreateUser() {}
__declspec(dllexport) void EOS_KWS_GetPermissionByKey() {}
__declspec(dllexport) void EOS_KWS_GetPermissionsCount() {}
__declspec(dllexport) void EOS_KWS_PermissionStatus_Release() {}
__declspec(dllexport) void EOS_KWS_QueryAgeGate() {}
__declspec(dllexport) void EOS_KWS_QueryPermissions() {}
__declspec(dllexport) void EOS_KWS_RemoveNotifyPermissionsUpdateReceived() {}
__declspec(dllexport) void EOS_KWS_RequestPermissions() {}
__declspec(dllexport) void EOS_KWS_UpdateParentEmail() {}
__declspec(dllexport) void EOS_Leaderboards_CopyLeaderboardDefinitionByIndex() {}
__declspec(dllexport) void EOS_Leaderboards_CopyLeaderboardDefinitionByLeaderboardId() {}
__declspec(dllexport) void EOS_Leaderboards_CopyLeaderboardRecordByIndex() {}
__declspec(dllexport) void EOS_Leaderboards_CopyLeaderboardRecordByUserId() {}
__declspec(dllexport) void EOS_Leaderboards_CopyLeaderboardUserScoreByIndex() {}
__declspec(dllexport) void EOS_Leaderboards_CopyLeaderboardUserScoreByUserId() {}
__declspec(dllexport) void EOS_Leaderboards_Definition_Release() {}
__declspec(dllexport) void EOS_Leaderboards_GetLeaderboardDefinitionCount() {}
__declspec(dllexport) void EOS_Leaderboards_GetLeaderboardRecordCount() {}
__declspec(dllexport) void EOS_Leaderboards_GetLeaderboardUserScoreCount() {}
__declspec(dllexport) void EOS_Leaderboards_LeaderboardDefinition_Release() {}
__declspec(dllexport) void EOS_Leaderboards_LeaderboardRecord_Release() {}
__declspec(dllexport) void EOS_Leaderboards_LeaderboardUserScore_Release() {}
__declspec(dllexport) void EOS_Leaderboards_QueryLeaderboardDefinitions() {}
__declspec(dllexport) void EOS_Leaderboards_QueryLeaderboardRanks() {}
__declspec(dllexport) void EOS_Leaderboards_QueryLeaderboardUserScores() {}
__declspec(dllexport) void EOS_LobbyDetails_CopyAttributeByIndex() {}
__declspec(dllexport) void EOS_LobbyDetails_CopyAttributeByKey() {}
__declspec(dllexport) void EOS_LobbyDetails_CopyInfo() {}
__declspec(dllexport) void EOS_LobbyDetails_CopyMemberAttributeByIndex() {}
__declspec(dllexport) void EOS_LobbyDetails_CopyMemberAttributeByKey() {}
__declspec(dllexport) void EOS_LobbyDetails_CopyMemberInfo() {}
__declspec(dllexport) void EOS_LobbyDetails_GetAttributeCount() {}
__declspec(dllexport) void EOS_LobbyDetails_GetLobbyOwner() {}
__declspec(dllexport) void EOS_LobbyDetails_GetMemberAttributeCount() {}
__declspec(dllexport) void EOS_LobbyDetails_GetMemberByIndex() {}
__declspec(dllexport) void EOS_LobbyDetails_GetMemberCount() {}
__declspec(dllexport) void EOS_LobbyDetails_Info_Release() {}
__declspec(dllexport) void EOS_LobbyDetails_MemberInfo_Release() {}
__declspec(dllexport) void EOS_LobbyDetails_Release() {}
__declspec(dllexport) void EOS_LobbyModification_AddAttribute() {}
__declspec(dllexport) void EOS_LobbyModification_AddMemberAttribute() {}
__declspec(dllexport) void EOS_LobbyModification_Release() {}
__declspec(dllexport) void EOS_LobbyModification_RemoveAttribute() {}
__declspec(dllexport) void EOS_LobbyModification_RemoveMemberAttribute() {}
__declspec(dllexport) void EOS_LobbyModification_SetAllowedPlatformIds() {}
__declspec(dllexport) void EOS_LobbyModification_SetBucketId() {}
__declspec(dllexport) void EOS_LobbyModification_SetInvitesAllowed() {}
__declspec(dllexport) void EOS_LobbyModification_SetMaxMembers() {}
__declspec(dllexport) void EOS_LobbyModification_SetPermissionLevel() {}
__declspec(dllexport) void EOS_LobbySearch_CopySearchResultByIndex() {}
__declspec(dllexport) void EOS_LobbySearch_Find() {}
__declspec(dllexport) void EOS_LobbySearch_GetSearchResultCount() {}
__declspec(dllexport) void EOS_LobbySearch_Release() {}
__declspec(dllexport) void EOS_LobbySearch_RemoveParameter() {}
__declspec(dllexport) void EOS_LobbySearch_SetLobbyId() {}
__declspec(dllexport) void EOS_LobbySearch_SetMaxResults() {}
__declspec(dllexport) void EOS_LobbySearch_SetParameter() {}
__declspec(dllexport) void EOS_LobbySearch_SetTargetUserId() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyJoinLobbyAccepted() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyLeaveLobbyRequested() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyLobbyInviteAccepted() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyLobbyInviteReceived() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyLobbyInviteRejected() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyLobbyMemberStatusReceived() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyLobbyMemberUpdateReceived() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyLobbyUpdateReceived() {}
__declspec(dllexport) void EOS_Lobby_AddNotifyRTCRoomConnectionChanged() {}
__declspec(dllexport) void EOS_Lobby_AddNotifySendLobbyNativeInviteRequested() {}
__declspec(dllexport) void EOS_Lobby_Attribute_Release() {}
__declspec(dllexport) void EOS_Lobby_CopyLobbyDetailsHandle() {}
__declspec(dllexport) void EOS_Lobby_CopyLobbyDetailsHandleByInviteId() {}
__declspec(dllexport) void EOS_Lobby_CopyLobbyDetailsHandleByUiEventId() {}
__declspec(dllexport) void EOS_Lobby_CreateLobby() {}
__declspec(dllexport) void EOS_Lobby_CreateLobbySearch() {}
__declspec(dllexport) void EOS_Lobby_DestroyLobby() {}
__declspec(dllexport) void EOS_Lobby_GetConnectString() {}
__declspec(dllexport) void EOS_Lobby_GetInviteCount() {}
__declspec(dllexport) void EOS_Lobby_GetInviteIdByIndex() {}
__declspec(dllexport) void EOS_Lobby_GetRTCRoomName() {}
__declspec(dllexport) void EOS_Lobby_HardMuteMember() {}
__declspec(dllexport) void EOS_Lobby_IsRTCRoomConnected() {}
__declspec(dllexport) void EOS_Lobby_JoinLobby() {}
__declspec(dllexport) void EOS_Lobby_JoinLobbyById() {}
__declspec(dllexport) void EOS_Lobby_KickMember() {}
__declspec(dllexport) void EOS_Lobby_LeaveLobby() {}
__declspec(dllexport) void EOS_Lobby_ParseConnectString() {}
__declspec(dllexport) void EOS_Lobby_PromoteMember() {}
__declspec(dllexport) void EOS_Lobby_QueryInvites() {}
__declspec(dllexport) void EOS_Lobby_RejectInvite() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyJoinLobbyAccepted() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyLeaveLobbyRequested() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyLobbyInviteAccepted() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyLobbyInviteReceived() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyLobbyInviteRejected() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyLobbyMemberStatusReceived() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyLobbyMemberUpdateReceived() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyLobbyUpdateReceived() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifyRTCRoomConnectionChanged() {}
__declspec(dllexport) void EOS_Lobby_RemoveNotifySendLobbyNativeInviteRequested() {}
__declspec(dllexport) void EOS_Lobby_SendInvite() {}
__declspec(dllexport) void EOS_Lobby_UpdateLobby() {}
__declspec(dllexport) void EOS_Lobby_UpdateLobbyModification() {}
__declspec(dllexport) void EOS_Logging_SetCallback() {}
__declspec(dllexport) void EOS_Logging_SetLogLevel() {}
__declspec(dllexport) void EOS_Mercury_Initialize() {}
__declspec(dllexport) void EOS_Mercury_Shutdown() {}
__declspec(dllexport) void EOS_Mercury_Tick() {}
__declspec(dllexport) void EOS_Metrics_BeginPlayerSession() {}
__declspec(dllexport) void EOS_Metrics_EndPlayerSession() {}
__declspec(dllexport) void EOS_Mods_CopyModInfo() {}
__declspec(dllexport) void EOS_Mods_EnumerateMods() {}
__declspec(dllexport) void EOS_Mods_InstallMod() {}
__declspec(dllexport) void EOS_Mods_ModInfo_Release() {}
__declspec(dllexport) void EOS_Mods_UninstallMod() {}
__declspec(dllexport) void EOS_Mods_UpdateMod() {}
__declspec(dllexport) void EOS_P2P_AcceptConnection() {}
__declspec(dllexport) void EOS_P2P_AddNotifyIncomingPacketQueueFull() {}
__declspec(dllexport) void EOS_P2P_AddNotifyPeerConnectionClosed() {}
__declspec(dllexport) void EOS_P2P_AddNotifyPeerConnectionEstablished() {}
__declspec(dllexport) void EOS_P2P_AddNotifyPeerConnectionInterrupted() {}
__declspec(dllexport) void EOS_P2P_AddNotifyPeerConnectionRequest() {}
__declspec(dllexport) void EOS_P2P_ClearPacketQueue() {}
__declspec(dllexport) void EOS_P2P_CloseConnection() {}
__declspec(dllexport) void EOS_P2P_CloseConnections() {}
__declspec(dllexport) void EOS_P2P_GetNATType() {}
__declspec(dllexport) void EOS_P2P_GetNextReceivedPacketSize() {}
__declspec(dllexport) void EOS_P2P_GetPacketQueueInfo() {}
__declspec(dllexport) void EOS_P2P_GetPortRange() {}
__declspec(dllexport) void EOS_P2P_GetRelayControl() {}
__declspec(dllexport) void EOS_P2P_QueryNATType() {}
__declspec(dllexport) void EOS_P2P_ReceivePacket() {}
__declspec(dllexport) void EOS_P2P_RemoveNotifyIncomingPacketQueueFull() {}
__declspec(dllexport) void EOS_P2P_RemoveNotifyPeerConnectionClosed() {}
__declspec(dllexport) void EOS_P2P_RemoveNotifyPeerConnectionEstablished() {}
__declspec(dllexport) void EOS_P2P_RemoveNotifyPeerConnectionInterrupted() {}
__declspec(dllexport) void EOS_P2P_RemoveNotifyPeerConnectionRequest() {}
__declspec(dllexport) void EOS_P2P_SendPacket() {}
__declspec(dllexport) void EOS_P2P_SetPacketQueueSize() {}
__declspec(dllexport) void EOS_P2P_SetPortRange() {}
__declspec(dllexport) void EOS_P2P_SetRelayControl() {}
__declspec(dllexport) void EOS_Platform_CheckForLauncherAndRestart() {}
__declspec(dllexport) void EOS_Platform_Create() {}
__declspec(dllexport) void EOS_Platform_GetAchievementsInterface() {}
__declspec(dllexport) void EOS_Platform_GetActiveCountryCode() {}
__declspec(dllexport) void EOS_Platform_GetActiveLocaleCode() {}
__declspec(dllexport) void EOS_Platform_GetAntiCheatClientInterface() {}
__declspec(dllexport) void EOS_Platform_GetAntiCheatServerInterface() {}
__declspec(dllexport) void EOS_Platform_GetApplicationStatus() {}
__declspec(dllexport) void EOS_Platform_GetAuthInterface() {}
__declspec(dllexport) void EOS_Platform_GetConnectInterface() {}
__declspec(dllexport) void EOS_Platform_GetCustomInvitesInterface() {}
__declspec(dllexport) void EOS_Platform_GetDesktopCrossplayStatus() {}
__declspec(dllexport) void EOS_Platform_GetEcomInterface() {}
__declspec(dllexport) void EOS_Platform_GetFriendsInterface() {}
__declspec(dllexport) void EOS_Platform_GetIntegratedPlatformInterface() {}
__declspec(dllexport) void EOS_Platform_GetKWSInterface() {}
__declspec(dllexport) void EOS_Platform_GetLeaderboardsInterface() {}
__declspec(dllexport) void EOS_Platform_GetLobbyInterface() {}
__declspec(dllexport) void EOS_Platform_GetMetricsInterface() {}
__declspec(dllexport) void EOS_Platform_GetModsInterface() {}
__declspec(dllexport) void EOS_Platform_GetNetworkStatus() {}
__declspec(dllexport) void EOS_Platform_GetOverrideCountryCode() {}
__declspec(dllexport) void EOS_Platform_GetOverrideLocaleCode() {}
__declspec(dllexport) void EOS_Platform_GetP2PInterface() {}
__declspec(dllexport) void EOS_Platform_GetPlayerDataStorageInterface() {}
__declspec(dllexport) void EOS_Platform_GetPresenceInterface() {}
__declspec(dllexport) void EOS_Platform_GetProgressionSnapshotInterface() {}
__declspec(dllexport) void EOS_Platform_GetRTCAdminInterface() {}
__declspec(dllexport) void EOS_Platform_GetRTCInterface() {}
__declspec(dllexport) void EOS_Platform_GetReportsInterface() {}
__declspec(dllexport) void EOS_Platform_GetSanctionsInterface() {}
__declspec(dllexport) void EOS_Platform_GetSessionsInterface() {}
__declspec(dllexport) void EOS_Platform_GetStatsInterface() {}
__declspec(dllexport) void EOS_Platform_GetTitleStorageInterface() {}
__declspec(dllexport) void EOS_Platform_GetUIInterface() {}
__declspec(dllexport) void EOS_Platform_GetUserInfoInterface() {}
__declspec(dllexport) void EOS_Platform_Release() {}
__declspec(dllexport) void EOS_Platform_SetApplicationStatus() {}
__declspec(dllexport) void EOS_Platform_SetNetworkStatus() {}
__declspec(dllexport) void EOS_Platform_SetOverrideCountryCode() {}
__declspec(dllexport) void EOS_Platform_SetOverrideLocaleCode() {}
__declspec(dllexport) void EOS_Platform_Tick() {}
__declspec(dllexport) void EOS_PlayerDataStorageFileTransferRequest_CancelRequest() {}
__declspec(dllexport) void EOS_PlayerDataStorageFileTransferRequest_GetFileRequestState() {}
__declspec(dllexport) void EOS_PlayerDataStorageFileTransferRequest_GetFilename() {}
__declspec(dllexport) void EOS_PlayerDataStorageFileTransferRequest_Release() {}
__declspec(dllexport) void EOS_PlayerDataStorage_CopyFileMetadataAtIndex() {}
__declspec(dllexport) void EOS_PlayerDataStorage_CopyFileMetadataByFilename() {}
__declspec(dllexport) void EOS_PlayerDataStorage_DeleteCache() {}
__declspec(dllexport) void EOS_PlayerDataStorage_DeleteFile() {}
__declspec(dllexport) void EOS_PlayerDataStorage_DuplicateFile() {}
__declspec(dllexport) void EOS_PlayerDataStorage_FileMetadata_Release() {}
__declspec(dllexport) void EOS_PlayerDataStorage_GetFileMetadataCount() {}
__declspec(dllexport) void EOS_PlayerDataStorage_QueryFile() {}
__declspec(dllexport) void EOS_PlayerDataStorage_QueryFileList() {}
__declspec(dllexport) void EOS_PlayerDataStorage_ReadFile() {}
__declspec(dllexport) void EOS_PlayerDataStorage_WriteFile() {}
__declspec(dllexport) void EOS_PresenceModification_DeleteData() {}
__declspec(dllexport) void EOS_PresenceModification_Release() {}
__declspec(dllexport) void EOS_PresenceModification_SetData() {}
__declspec(dllexport) void EOS_PresenceModification_SetJoinInfo() {}
__declspec(dllexport) void EOS_PresenceModification_SetRawRichText() {}
__declspec(dllexport) void EOS_PresenceModification_SetStatus() {}
__declspec(dllexport) void EOS_Presence_AddNotifyJoinGameAccepted() {}
__declspec(dllexport) void EOS_Presence_AddNotifyOnPresenceChanged() {}
__declspec(dllexport) void EOS_Presence_CopyPresence() {}
__declspec(dllexport) void EOS_Presence_CreatePresenceModification() {}
__declspec(dllexport) void EOS_Presence_GetJoinInfo() {}
__declspec(dllexport) void EOS_Presence_HasPresence() {}
__declspec(dllexport) void EOS_Presence_Info_Release() {}
__declspec(dllexport) void EOS_Presence_QueryPresence() {}
__declspec(dllexport) void EOS_Presence_RemoveNotifyJoinGameAccepted() {}
__declspec(dllexport) void EOS_Presence_RemoveNotifyOnPresenceChanged() {}
__declspec(dllexport) void EOS_Presence_SetPresence() {}
__declspec(dllexport) void EOS_ProductUserId_FromString() {}
__declspec(dllexport) void EOS_ProductUserId_IsValid() {}
__declspec(dllexport) void EOS_ProductUserId_ToString() {}
__declspec(dllexport) void EOS_ProgressionSnapshot_AddProgression() {}
__declspec(dllexport) void EOS_ProgressionSnapshot_BeginSnapshot() {}
__declspec(dllexport) void EOS_ProgressionSnapshot_DeleteSnapshot() {}
__declspec(dllexport) void EOS_ProgressionSnapshot_EndSnapshot() {}
__declspec(dllexport) void EOS_ProgressionSnapshot_SubmitSnapshot() {}
__declspec(dllexport) void EOS_RTCAdmin_CopyUserTokenByIndex() {}
__declspec(dllexport) void EOS_RTCAdmin_CopyUserTokenByUserId() {}
__declspec(dllexport) void EOS_RTCAdmin_Kick() {}
__declspec(dllexport) void EOS_RTCAdmin_QueryJoinRoomToken() {}
__declspec(dllexport) void EOS_RTCAdmin_SetParticipantHardMute() {}
__declspec(dllexport) void EOS_RTCAdmin_UserToken_Release() {}
__declspec(dllexport) void EOS_RTCAudio_AddNotifyAudioBeforeRender() {}
__declspec(dllexport) void EOS_RTCAudio_AddNotifyAudioBeforeSend() {}
__declspec(dllexport) void EOS_RTCAudio_AddNotifyAudioDevicesChanged() {}
__declspec(dllexport) void EOS_RTCAudio_AddNotifyAudioInputState() {}
__declspec(dllexport) void EOS_RTCAudio_AddNotifyAudioOutputState() {}
__declspec(dllexport) void EOS_RTCAudio_AddNotifyParticipantUpdated() {}
__declspec(dllexport) void EOS_RTCAudio_CopyInputDeviceInformationByIndex() {}
__declspec(dllexport) void EOS_RTCAudio_CopyOutputDeviceInformationByIndex() {}
__declspec(dllexport) void EOS_RTCAudio_GetAudioInputDeviceByIndex() {}
__declspec(dllexport) void EOS_RTCAudio_GetAudioInputDevicesCount() {}
__declspec(dllexport) void EOS_RTCAudio_GetAudioOutputDeviceByIndex() {}
__declspec(dllexport) void EOS_RTCAudio_GetAudioOutputDevicesCount() {}
__declspec(dllexport) void EOS_RTCAudio_GetInputDevicesCount() {}
__declspec(dllexport) void EOS_RTCAudio_GetOutputDevicesCount() {}
__declspec(dllexport) void EOS_RTCAudio_InputDeviceInformation_Release() {}
__declspec(dllexport) void EOS_RTCAudio_OutputDeviceInformation_Release() {}
__declspec(dllexport) void EOS_RTCAudio_QueryInputDevicesInformation() {}
__declspec(dllexport) void EOS_RTCAudio_QueryOutputDevicesInformation() {}
__declspec(dllexport) void EOS_RTCAudio_RegisterPlatformAudioUser() {}
__declspec(dllexport) void EOS_RTCAudio_RegisterPlatformUser() {}
__declspec(dllexport) void EOS_RTCAudio_RemoveNotifyAudioBeforeRender() {}
__declspec(dllexport) void EOS_RTCAudio_RemoveNotifyAudioBeforeSend() {}
__declspec(dllexport) void EOS_RTCAudio_RemoveNotifyAudioDevicesChanged() {}
__declspec(dllexport) void EOS_RTCAudio_RemoveNotifyAudioInputState() {}
__declspec(dllexport) void EOS_RTCAudio_RemoveNotifyAudioOutputState() {}
__declspec(dllexport) void EOS_RTCAudio_RemoveNotifyParticipantUpdated() {}
__declspec(dllexport) void EOS_RTCAudio_SendAudio() {}
__declspec(dllexport) void EOS_RTCAudio_SetAudioInputSettings() {}
__declspec(dllexport) void EOS_RTCAudio_SetAudioOutputSettings() {}
__declspec(dllexport) void EOS_RTCAudio_SetInputDeviceSettings() {}
__declspec(dllexport) void EOS_RTCAudio_SetOutputDeviceSettings() {}
__declspec(dllexport) void EOS_RTCAudio_SetPosition() {}
__declspec(dllexport) void EOS_RTCAudio_UnregisterPlatformAudioUser() {}
__declspec(dllexport) void EOS_RTCAudio_UnregisterPlatformUser() {}
__declspec(dllexport) void EOS_RTCAudio_UpdateParticipantVolume() {}
__declspec(dllexport) void EOS_RTCAudio_UpdateReceiving() {}
__declspec(dllexport) void EOS_RTCAudio_UpdateReceivingVolume() {}
__declspec(dllexport) void EOS_RTCAudio_UpdateSending() {}
__declspec(dllexport) void EOS_RTCAudio_UpdateSendingVolume() {}
__declspec(dllexport) void EOS_RTCData_AddNotifyDataReceived() {}
__declspec(dllexport) void EOS_RTCData_AddNotifyParticipantUpdated() {}
__declspec(dllexport) void EOS_RTCData_RemoveNotifyDataReceived() {}
__declspec(dllexport) void EOS_RTCData_RemoveNotifyParticipantUpdated() {}
__declspec(dllexport) void EOS_RTCData_SendData() {}
__declspec(dllexport) void EOS_RTCData_UpdateReceiving() {}
__declspec(dllexport) void EOS_RTCData_UpdateSending() {}
__declspec(dllexport) void EOS_RTCVideo_AddNotifyParticipantUpdated() {}
__declspec(dllexport) void EOS_RTCVideo_AddNotifyVideoReceived() {}
__declspec(dllexport) void EOS_RTCVideo_CreateOutgoingVideoFrameFormat() {}
__declspec(dllexport) void EOS_RTCVideo_RemoveNotifyParticipantUpdated() {}
__declspec(dllexport) void EOS_RTCVideo_RemoveNotifyVideoReceived() {}
__declspec(dllexport) void EOS_RTCVideo_SendVideo() {}
__declspec(dllexport) void EOS_RTCVideo_SetAdaptVideoFrameCallback() {}
__declspec(dllexport) void EOS_RTCVideo_SetVideoAllocationCallback() {}
__declspec(dllexport) void EOS_RTCVideo_SetVideoReleaseCallback() {}
__declspec(dllexport) void EOS_RTCVideo_UpdateReceiving() {}
__declspec(dllexport) void EOS_RTCVideo_UpdateSending() {}
__declspec(dllexport) void EOS_RTC_AddNotifyDisconnected() {}
__declspec(dllexport) void EOS_RTC_AddNotifyParticipantStatusChanged() {}
__declspec(dllexport) void EOS_RTC_AddNotifyRoomStatisticsUpdated() {}
__declspec(dllexport) void EOS_RTC_BlockParticipant() {}
__declspec(dllexport) void EOS_RTC_GetAudioInterface() {}
__declspec(dllexport) void EOS_RTC_GetDataInterface() {}
__declspec(dllexport) void EOS_RTC_JoinRoom() {}
__declspec(dllexport) void EOS_RTC_LeaveRoom() {}
__declspec(dllexport) void EOS_RTC_RemoveNotifyDisconnected() {}
__declspec(dllexport) void EOS_RTC_RemoveNotifyParticipantStatusChanged() {}
__declspec(dllexport) void EOS_RTC_RemoveNotifyRoomStatisticsUpdated() {}
__declspec(dllexport) void EOS_RTC_SetRoomSetting() {}
__declspec(dllexport) void EOS_RTC_SetSetting() {}
__declspec(dllexport) void EOS_Reports_SendPlayerBehaviorReport() {}
__declspec(dllexport) void EOS_Sanctions_CopyPlayerSanctionByIndex() {}
__declspec(dllexport) void EOS_Sanctions_CreatePlayerSanctionAppeal() {}
__declspec(dllexport) void EOS_Sanctions_GetPlayerSanctionCount() {}
__declspec(dllexport) void EOS_Sanctions_PlayerSanction_Release() {}
__declspec(dllexport) void EOS_Sanctions_QueryActivePlayerSanctions() {}
__declspec(dllexport) void EOS_SessionDetails_Attribute_Release() {}
__declspec(dllexport) void EOS_SessionDetails_CopyInfo() {}
__declspec(dllexport) void EOS_SessionDetails_CopySessionAttributeByIndex() {}
__declspec(dllexport) void EOS_SessionDetails_CopySessionAttributeByKey() {}
__declspec(dllexport) void EOS_SessionDetails_GetSessionAttributeCount() {}
__declspec(dllexport) void EOS_SessionDetails_Info_Release() {}
__declspec(dllexport) void EOS_SessionDetails_Release() {}
__declspec(dllexport) void EOS_SessionModification_AddAttribute() {}
__declspec(dllexport) void EOS_SessionModification_Release() {}
__declspec(dllexport) void EOS_SessionModification_RemoveAttribute() {}
__declspec(dllexport) void EOS_SessionModification_SetAllowedPlatformIds() {}
__declspec(dllexport) void EOS_SessionModification_SetBucketId() {}
__declspec(dllexport) void EOS_SessionModification_SetHostAddress() {}
__declspec(dllexport) void EOS_SessionModification_SetInvitesAllowed() {}
__declspec(dllexport) void EOS_SessionModification_SetJoinInProgressAllowed() {}
__declspec(dllexport) void EOS_SessionModification_SetMaxPlayers() {}
__declspec(dllexport) void EOS_SessionModification_SetPermissionLevel() {}
__declspec(dllexport) void EOS_SessionSearch_CopySearchResultByIndex() {}
__declspec(dllexport) void EOS_SessionSearch_Find() {}
__declspec(dllexport) void EOS_SessionSearch_GetSearchResultCount() {}
__declspec(dllexport) void EOS_SessionSearch_Release() {}
__declspec(dllexport) void EOS_SessionSearch_RemoveParameter() {}
__declspec(dllexport) void EOS_SessionSearch_SetMaxResults() {}
__declspec(dllexport) void EOS_SessionSearch_SetParameter() {}
__declspec(dllexport) void EOS_SessionSearch_SetSessionId() {}
__declspec(dllexport) void EOS_SessionSearch_SetTargetUserId() {}
__declspec(dllexport) void EOS_Sessions_AddNotifyJoinSessionAccepted() {}
__declspec(dllexport) void EOS_Sessions_AddNotifyLeaveSessionRequested() {}
__declspec(dllexport) void EOS_Sessions_AddNotifySendSessionNativeInviteRequested() {}
__declspec(dllexport) void EOS_Sessions_AddNotifySessionInviteAccepted() {}
__declspec(dllexport) void EOS_Sessions_AddNotifySessionInviteReceived() {}
__declspec(dllexport) void EOS_Sessions_AddNotifySessionInviteRejected() {}
__declspec(dllexport) void EOS_Sessions_CopyActiveSessionHandle() {}
__declspec(dllexport) void EOS_Sessions_CopySessionHandleByInviteId() {}
__declspec(dllexport) void EOS_Sessions_CopySessionHandleByUiEventId() {}
__declspec(dllexport) void EOS_Sessions_CopySessionHandleForPresence() {}
__declspec(dllexport) void EOS_Sessions_CreateSessionModification() {}
__declspec(dllexport) void EOS_Sessions_CreateSessionSearch() {}
__declspec(dllexport) void EOS_Sessions_DestroySession() {}
__declspec(dllexport) void EOS_Sessions_DumpSessionState() {}
__declspec(dllexport) void EOS_Sessions_EndSession() {}
__declspec(dllexport) void EOS_Sessions_GetInviteCount() {}
__declspec(dllexport) void EOS_Sessions_GetInviteIdByIndex() {}
__declspec(dllexport) void EOS_Sessions_IsUserInSession() {}
__declspec(dllexport) void EOS_Sessions_JoinSession() {}
__declspec(dllexport) void EOS_Sessions_QueryInvites() {}
__declspec(dllexport) void EOS_Sessions_RegisterPlayers() {}
__declspec(dllexport) void EOS_Sessions_RejectInvite() {}
__declspec(dllexport) void EOS_Sessions_RemoveNotifyJoinSessionAccepted() {}
__declspec(dllexport) void EOS_Sessions_RemoveNotifyLeaveSessionRequested() {}
__declspec(dllexport) void EOS_Sessions_RemoveNotifySendSessionNativeInviteRequested() {}
__declspec(dllexport) void EOS_Sessions_RemoveNotifySessionInviteAccepted() {}
__declspec(dllexport) void EOS_Sessions_RemoveNotifySessionInviteReceived() {}
__declspec(dllexport) void EOS_Sessions_RemoveNotifySessionInviteRejected() {}
__declspec(dllexport) void EOS_Sessions_SendInvite() {}
__declspec(dllexport) void EOS_Sessions_StartSession() {}
__declspec(dllexport) void EOS_Sessions_UnregisterPlayers() {}
__declspec(dllexport) void EOS_Sessions_UpdateSession() {}
__declspec(dllexport) void EOS_Sessions_UpdateSessionModification() {}
__declspec(dllexport) void EOS_Shutdown() {}
__declspec(dllexport) void EOS_Stats_CopyStatByIndex() {}
__declspec(dllexport) void EOS_Stats_CopyStatByName() {}
__declspec(dllexport) void EOS_Stats_GetStatsCount() {}
__declspec(dllexport) void EOS_Stats_IngestStat() {}
__declspec(dllexport) void EOS_Stats_QueryStats() {}
__declspec(dllexport) void EOS_Stats_Stat_Release() {}
__declspec(dllexport) void EOS_TitleStorageFileTransferRequest_CancelRequest() {}
__declspec(dllexport) void EOS_TitleStorageFileTransferRequest_GetFileRequestState() {}
__declspec(dllexport) void EOS_TitleStorageFileTransferRequest_GetFilename() {}
__declspec(dllexport) void EOS_TitleStorageFileTransferRequest_Release() {}
__declspec(dllexport) void EOS_TitleStorage_CopyFileMetadataAtIndex() {}
__declspec(dllexport) void EOS_TitleStorage_CopyFileMetadataByFilename() {}
__declspec(dllexport) void EOS_TitleStorage_DeleteCache() {}
__declspec(dllexport) void EOS_TitleStorage_FileMetadata_Release() {}
__declspec(dllexport) void EOS_TitleStorage_GetFileMetadataCount() {}
__declspec(dllexport) void EOS_TitleStorage_QueryFile() {}
__declspec(dllexport) void EOS_TitleStorage_QueryFileList() {}
__declspec(dllexport) void EOS_TitleStorage_ReadFile() {}
__declspec(dllexport) void EOS_UI_AcknowledgeEventId() {}
__declspec(dllexport) void EOS_UI_AddNotifyDisplaySettingsUpdated() {}
__declspec(dllexport) void EOS_UI_AddNotifyMemoryMonitor() {}
__declspec(dllexport) void EOS_UI_GetFriendsExclusiveInput() {}
__declspec(dllexport) void EOS_UI_GetFriendsVisible() {}
__declspec(dllexport) void EOS_UI_GetNotificationLocationPreference() {}
__declspec(dllexport) void EOS_UI_GetToggleFriendsButton() {}
__declspec(dllexport) void EOS_UI_GetToggleFriendsKey() {}
__declspec(dllexport) void EOS_UI_HideFriends() {}
__declspec(dllexport) void EOS_UI_IsSocialOverlayPaused() {}
__declspec(dllexport) void EOS_UI_IsValidButtonCombination() {}
__declspec(dllexport) void EOS_UI_IsValidKeyCombination() {}
__declspec(dllexport) void EOS_UI_PauseSocialOverlay() {}
__declspec(dllexport) void EOS_UI_PrePresent() {}
__declspec(dllexport) void EOS_UI_RemoveNotifyDisplaySettingsUpdated() {}
__declspec(dllexport) void EOS_UI_RemoveNotifyMemoryMonitor() {}
__declspec(dllexport) void EOS_UI_ReportInputState() {}
__declspec(dllexport) void EOS_UI_SetDisplayPreference() {}
__declspec(dllexport) void EOS_UI_SetToggleFriendsButton() {}
__declspec(dllexport) void EOS_UI_SetToggleFriendsKey() {}
__declspec(dllexport) void EOS_UI_ShowBlockPlayer() {}
__declspec(dllexport) void EOS_UI_ShowFriends() {}
__declspec(dllexport) void EOS_UI_ShowNativeProfile() {}
__declspec(dllexport) void EOS_UI_ShowReportPlayer() {}
__declspec(dllexport) void EOS_UserInfo_BestDisplayName_Release() {}
__declspec(dllexport) void EOS_UserInfo_CopyBestDisplayName() {}
__declspec(dllexport) void EOS_UserInfo_CopyBestDisplayNameWithPlatform() {}
__declspec(dllexport) void EOS_UserInfo_CopyExternalUserInfoByAccountId() {}
__declspec(dllexport) void EOS_UserInfo_CopyExternalUserInfoByAccountType() {}
__declspec(dllexport) void EOS_UserInfo_CopyExternalUserInfoByIndex() {}
__declspec(dllexport) void EOS_UserInfo_CopyUserInfo() {}
__declspec(dllexport) void EOS_UserInfo_ExternalUserInfo_Release() {}
__declspec(dllexport) void EOS_UserInfo_GetExternalUserInfoCount() {}
__declspec(dllexport) void EOS_UserInfo_GetLocalPlatformType() {}
__declspec(dllexport) void EOS_UserInfo_QueryUserInfo() {}
__declspec(dllexport) void EOS_UserInfo_QueryUserInfoByDisplayName() {}
__declspec(dllexport) void EOS_UserInfo_QueryUserInfoByExternalAccount() {}
__declspec(dllexport) void EOS_UserInfo_Release() {}

}
