name: Build DLL

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Build DLL
      run: |
        cl /LD eos_stub.cpp /Fe:eos_stub.dll
        powershell Compress-Archive eos_stub.dll eos_stub.zip

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: eos_stub.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
