name: Build DLL

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build DLL
      run: cl /LD eos_stub.cpp /Fe:eos_stub.dll

    - name: Zip output
      run: powershell Compress-Archive eos_stub.dll eos_stub.zip

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: eos_stub.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
